config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"

  resources :articles, only: [:create, :index, :destroy]
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  validates :title, :url, presence: true
  belongs_to :user

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  attr_reader :password

  has_many :articles

  after_initialize :ensure_session_token

  validates :password_digest, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true


  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    url = params["url"] ? params["url"] : 'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'
    @section = params["section"] ? params["section"] : "NYTimes.com Home Page (U.S.)"

    require 'rss'
    require 'uri'
    open(url) do |rss|
      feed = RSS::Parser.parse(rss)
      @articles = feed.items
    end
    render :index
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_url(params)
    else
      flash.now[:errors] = @article.errors.full_messages
      redirect_to articles_url(params)
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    if params.has_key?(:profile)
      redirect_to user_path
    else
      redirect_to articles_url(params)
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :url, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to articles_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_signed_in!, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to articles_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:password, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    token =<<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
    token.html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_favorites.html.erb
<% if !current_user %>
  <em>
    <%= link_to '<i class="glyphicon glyphicon-star-empty"></i>
                  Sign in to add this article to your favorites.'.html_safe,
                  new_session_path %>
  </em>

<% elsif current_user.articles.exists?(url: article.link) %>
  <% saved_article = Article.find_by(url: article.link) %>
  <%= link_to '<span class="glyphicon glyphicon-star"></i>'.html_safe,
                      article_path(saved_article,
                      url: params["url"],
                      section: params["section"]),
                      method: "delete" %>
                      <em>(This articles is saved as one of your favorites.
                          Click the star to remove this article.)</em>

<% else %>
  <%= link_to '<span class="glyphicon glyphicon-star-empty"></i>'.html_safe,
                      {controller: "articles",
                       action: "create",
                       article: {
                         user_id: current_user.id,
                         title: article.title,
                         url: article.link
                       },
                       url: params["url"],
                       section: params["section"]
                       },
                       method: "post" %>
                       <em>(Click the star to add article to your favorites)</em>
 <% end %>

app/views/articles/_sections.html.erb
<h3>Beyond the <%= @section %>: Other Sections of the New York Times </h3>
<div class="additional-sections">
  <ul>
    <li><%= link_to "NYTimes.com Home Page (International Edition)",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/InternationalHome.xml',
    section: "NYTimes.com Home Page (International Edition)") %></li>

    <li><%= link_to "World News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/World.xml',
    section: "World News") %></li>

    <li><%= link_to "US News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/US.xml',
    section: "US News") %></li>

    <li><%= link_to "NY/Region News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml',
    section: "NY/Region News") %></li>

    <li><%= link_to "Business News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
    section: "Business News") %></li>

    <li><%= link_to "Technology News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml',
    section: "Technology News") %></li>

    <li><%= link_to "Sports News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml',
    section: "Sports News") %></li>

    <li><%= link_to "Science News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/Science.xml',
    section: "Science News") %></li>

    <li><%= link_to "Health News",
    articles_path(url: 'http://rss.nytimes.com/services/xml/rss/nyt/Health.xml',
    section: "Health News") %></li>
  </ul>
</div>

app/views/articles/index.html.erb
  <h3 class="section-headline"><%= @section %></h3>

  <p class="scroll-msg">
    <% if current_user %>
      <em>Hi <%= current_user.user_name %></em>!
    <% end %>
    <em>Want to see more than just <%= @section %>? <br>
      Scroll down for feeds from other sections of </em>The Times.
  </p>

  <% if current_user %>
    <%= link_to "See your saved articles", user_path(current_user) %>
  <% end %>

  <div class="articles-list">
    <% @articles.each do |article| %>
      <h3><%=  article.title %></h3>
      <em>Published on <%= article.date %></em>.
      <br>
      <%= link_to("Read the article online", article.link) %>
      <br>
      <%= render 'articles/favorites', article: article %>
    <% end %>
  </div>

<br>

<%= render 'articles/sections' %>

app/views/layouts/_error_messages.html.erb
<% if flash[:errors] %>
  <div class="error-messages">
    <%= flash[:errors].join("<br>").html_safe %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="new-year">
    <span>Happy New Year Good Dog Team!  ~ Noah</span>
  </div>
    <div class="row">
      <ul>
        <li><a href="http://noahwiener.github.io/">Portfolio</a></li>
        <li><a href="https://www.linkedin.com/in/noahwiener">LinkedIn</a></li>
        <li><a href="https://github.com/noahwiener">Github</a> </li>
        <li><a href="http://noahwiener.github.io/ResumeNoahWiener.pdf">Resume</a></li>
        <li><a href="mailto:noah.wiener@gmail.com">Contact</a></li>
      </ul>
    </div>

</footer>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="navbar-collapse collapse noah-nav">
  <ul class="nav navbar-nav">
    <%= link_to '<img src="/New-York-Times-Logo.jpg" height="60px">'.html_safe,
                        articles_path %>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <% if current_user %>
        <span>Hi, <%= current_user.user_name %></span>
        <%= link_to "Favorite Articles", user_path(current_user) %>
        <%= link_to "Sign Out", session_url, :method => :delete %>
      <% else %>
        <%= link_to "Sign In", new_session_url %> <%= link_to "Sign Up", new_user_url %>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssGoodDog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/navbar" %>
  <%= render "layouts/error_messages" %>

  <div class="frame">
    <div class="container">
      <div class="inner col-xs-10 col-xs-offset-1">
        <%= yield %>
      </div>
    </div>
  </div>
  
  <%= render "layouts/footer" %>

</body>
</html>

app/views/users/new.html.erb
<div class="login-content">

  <h2>Sign Up</h2>

  <form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <label>
      Username
      <input type="text" name="user[user_name]" value="">
    </label>
    <br>
    <label>
      Password
      <input type="password" name="user[password]" value="">
    </label>
    <br><br>
    <input type="submit" value="Sign Up">
  </form>

  <br>
    <em>Already have an account?</em>
    <br>
    <em><%= link_to "Click here to log in", new_session_url %></em>
    <br><br>
    <div class="row">
      <div class="rumo col-xs-2 col-xs-offset-4">
        <%= link_to '<img src="/dog.jpg">'.html_safe,
        {controller: "sessions", action: "create",
          user: {user_name: "Rumo", password: "rumopassword"}},
          method: "post"
         %>
      </div>
      <div class="alt-login-text col-xs-3">
        Or click on Noah's own Good Dog, Rumo, to log in as a guest.
      </div>
    </div>
</div>

app/views/users/show.html.erb
<h3 class="section-headline"><%= @user.user_name %>'s Favorite Articles</h3>
<%= link_to("<< Back to the New York Times feed", articles_path) %>

<div class="articles-list">
  <% if @user.articles.empty? %>
    Looks like you haven't saved any articles yet. Be a Good Dog and check out the
    <%= link_to("RSS feed here!", articles_path) %>
  <% else %>
    <% @user.articles.each do |article| %>
      <h3><%=  article.title %></h3>
      <%= link_to("Read the article on nytimes.com", article.url) %>
      <br>
      <%= link_to 'Remove from favorites',
                          article_path(article,
                          profile: true),
                          method: "delete" %>
                          <% end %>
  <% end %>
</div>